apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-add-host-mount
patch: |-
    - op: add
      path: /spec/controllerTemplate/spec/volumes/-
      value:
        name: shared-volume
        persistentVolumeClaim:
          claimName: sas-efs-shared-pvc
    - op: add
      path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
      value:
        name: shared-volume
        mountPath: /shared-data
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1