apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-efs-shared-pvc
  namespace: viya4
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-csi
  volumeMode: Filesystem
  resources:
    requests:
      storage: 256Gi